/* catalog.js — WHOLE FILE
   Catalog (no Owned):
   - Shows Characters, Weapons, Accessories, Bosses in one unified grid.
   - Search supports normal substring search and pasted lists.
   - Uses same view toggle as roster: body.mobile-compact / body.mobile-detailed
*/

const PLACEHOLDER_IMG = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='128' height='128'><rect width='100%' height='100%' fill='%23121522'/><text x='50%' y='50%' dominant-baseline='middle' text-anchor='middle' fill='%23aab1d6' font-family='Arial' font-size='14'>No Image</text></svg>";
const BAD_IMG_CACHE_KEY = "evertale_bad_img_urls_v1";
const BAD_IMG_CACHE = new Set(safeJsonParse(localStorage.getItem(BAD_IMG_CACHE_KEY), []));
const DATA = { characters:"./data/characters.json", weapons:"./data/weapons.json", accessories:"./data/accessories.json", bosses:"./data/bosses.json" };
const LS_MOBILE_VIEW_KEY = "evertale_mobile_view_v1";
const state = { items: [], q: "", type: "all", listTokens: null };
const $ = id => document.getElementById(id);

function safeJsonParse(raw, fallback){ try{return JSON.parse(raw)}catch{return fallback} }
function markBadImgUrl(url){ try{ if(!url)return; BAD_IMG_CACHE.add(url); localStorage.setItem(BAD_IMG_CACHE_KEY, JSON.stringify(Array.from(BAD_IMG_CACHE))); }catch{} }
function isBadImgUrl(url){ try{return !!url && BAD_IMG_CACHE.has(url)}catch{return false} }
function getMobileViewPref(){ const v=localStorage.getItem(LS_MOBILE_VIEW_KEY); return (v==="detailed"||v==="compact")?v:"compact"; }
function setMobileViewPref(v){ localStorage.setItem(LS_MOBILE_VIEW_KEY,v); }
function applyMobileViewClass(view){ document.body.classList.add("page-catalog"); document.body.classList.remove("mobile-compact","mobile-detailed"); document.body.classList.add(view==="detailed"?"mobile-detailed":"mobile-compact"); }
function syncViewToggleText(){ const btn=$("viewToggle"); if(btn){ const v=getMobileViewPref(); btn.textContent=`View: ${v==="compact"?"Compact":"Detailed"}`; } }
function safeText(s){ return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;"); }
function normKey(s){ return String(s??"").toLowerCase().replace(/[\u2019']/g,"").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," "); }
function normalizeElementDisplay(el){ const raw=String(el||'').trim(); return raw?raw.replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()):''; }
function normalizeSkillArray(arr){ return Array.isArray(arr)?arr.filter(Boolean):[]; }
function skillMetaText(skill){ const parts=[]; if(skill&&skill.tu!==undefined&&skill.tu!==null&&skill.tu!=='')parts.push(String(skill.tu)+' TU'); const sp=skill?(skill.sp??skill.spirit):null; if(sp!==undefined&&sp!==null&&sp!=='')parts.push((Number(sp)>0?'+':'')+String(sp)+' SP'); if(skill&&skill.targeting)parts.push(String(skill.targeting)); return parts.join(' • '); }
function renderSkillBoxes(title, skills, kindClass){ const rows=normalizeSkillArray(skills); if(!rows.length)return ''; const boxes=rows.map(s=>{ const name=safeText((s&&s.name)||'Unnamed'); const meta=safeText(skillMetaText(s)); const desc=safeText((s&&s.description)||'').replace(/\n/g,'<br>'); return '<div class="skillBox"><div class="skillBoxHead"><strong>'+name+'</strong>'+(meta?'<span>'+meta+'</span>':'')+'</div>'+(desc?'<div class="skillBoxText">'+desc+'</div>':'')+'</div>'; }).join(''); return '<div class="panel skillPanel '+(kindClass||'')+'"><div class="panelTitle">'+safeText(title)+'</div><div class="skillBoxList">'+boxes+'</div></div>'; }
function renderDescriptionPanel(item){ const desc=String(item.description||item.flavorText||'').trim(); if(!desc)return ''; const payload=encodeURIComponent(JSON.stringify(item.descriptionByForm||[])); const title=item.kind==="characters"?"Description":"Flavor Text"; return `<div class="panel descriptionPanel" data-descriptions="${safeText(payload)}"><div class="panelTitle">${safeText(title)}</div><div class="muted descriptionText" style="white-space:pre-wrap">${safeText(desc)}</div></div>`; }
function normalizeElementClass(el){ const e=String(el||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,''); if(e==='fire'||e==='flame')return'el-fire'; if(e==='water'||e==='ice')return'el-water'; if(e==='storm'||e==='air'||e==='wind'||e==='thunder'||e==='lightning'||e==='electric')return'el-storm'; if(e==='earth'||e==='terra'||e==='ground')return'el-earth'; if(e==='light'||e==='life'||e==='holy')return'el-light'; if(e==='dark'||e==='death'||e==='shadow')return'el-dark'; return e?`el-${e}`:''; }
function parseListTokens(text){ const parts=String(text??"").split(/[\n\r,;\t]+/g).map(s=>s.trim()).filter(Boolean); if(parts.length<=1)return null; const tokens=[]; const seen=new Set(); for(const p of parts){ const k=normKey(p); if(!k||seen.has(k))continue; seen.add(k); tokens.push(k); } return tokens.length?tokens:null; }
function matchesTokens(item,tokens){ const id=normKey(item.id), name=normKey(item.name), sub=normKey(item.subtitle); for(const t of tokens){ if(t===id||t===name||t===sub)return true; if(t.length>=4&&(name.includes(t)||sub.includes(t)))return true; } return false; }
async function fetchJson(url){ const res=await fetch(url,{cache:"no-store"}); if(!res.ok)throw new Error(`Failed to fetch ${url}: ${res.status}`); return await res.json(); }
async function fetchJsonOptional(url){ try{return await fetchJson(url)}catch(err){ console.warn('[Catalog] Optional JSON skipped:', url, err); return null; } }
function toArray(json,keyGuess){ if(Array.isArray(json))return json; if(json&&Array.isArray(json[keyGuess]))return json[keyGuess]; if(json&&Array.isArray(json.items))return json.items; return []; }
function pickFirst(...vals){ for(const v of vals) if(v!==undefined&&v!==null&&v!=="") return v; return ""; }
function imageUrlsFromCharacter(u){ const variants=Array.isArray(u.imageVariants)?u.imageVariants.map(v=>v&&v.url).filter(Boolean):[]; const large=Array.isArray(u.imagesLarge)?u.imagesLarge.filter(Boolean):[]; return variants.length?variants:(large.length?large:(u.image?[u.image]:[])); }
function normalizeFormSkillRows(forms, key){ return Array.isArray(forms)?forms.map(f=>({ state:f.state, sourceId:f.sourceId, rows:Array.isArray(f[key])?f[key]:[] })):[]; }
function legacyCharacterTitleMaps(legacyRows){ const byFamily=new Map(), byId=new Map(), byImageFamily=new Map(), byName=new Map(); for(const row of legacyRows||[]){ const title=String(row?.title||'').trim(); if(!title)continue; const family=String(row?.internal?.family||'').trim(); const monsterId=String(row?.internal?.monsterId||'').trim(); const id=String(row?.id||'').trim(); const name=String(row?.name||'').trim(); const image=String(row?.image||''); const imageFamily=(image.match(/characters\/([A-Za-z0-9_]+?)(?:0[123])?\.png/)||[])[1]; if(family&&!byFamily.has(family))byFamily.set(family,title); if(monsterId&&!byId.has(monsterId))byId.set(monsterId,title); if(id&&!byId.has(id))byId.set(id,title); if(imageFamily&&!byImageFamily.has(imageFamily))byImageFamily.set(imageFamily,title); if(name&&!byName.has(name))byName.set(name,title); } return {byFamily,byId,byImageFamily,byName}; }
function applyLegacyCharacterTitles(items, legacyRows){ const maps=legacyCharacterTitleMaps(legacyRows); return items.map(item=>{ if(item.kind!=="characters"||item.subtitle)return item; const byFamily=maps.byFamily.get(item.id)||maps.byFamily.get(item.family); const byId=maps.byId.get(item.id); const imgFamily=(String(item.image||'').match(/characters\/([A-Za-z0-9_]+?)(?:0[123])?\.png/)||[])[1]; const byImg=imgFamily?maps.byImageFamily.get(imgFamily):''; const byName=maps.byName.get(item.name); const title=pickFirst(byFamily,byId,byImg,byName,""); return title?{...item, subtitle:title}:item; }); }
function normalizeCharacters(arr){ const seen=new Set(); const out=[]; for(const u of arr){ const id=String(u?.id??u?.family??""); if(!id||seen.has(id))continue; seen.add(id); const atk=u.atk??u.stats?.atk??""; const hp=u.hp??u.stats?.hp??""; const spd=u.spd??u.stats?.spd??""; const cost=u.cost??u.stats?.cost??""; const imgs=imageUrlsFromCharacter(u); out.push({ kind:"characters", id, family:u.family||u.internal?.family||id, name:pickFirst(u.name,id), subtitle:pickFirst(u.title,u.subtitle,""), description:pickFirst(u.description,""), descriptionByForm:Array.isArray(u.descriptionByForm)?u.descriptionByForm:[], rarity:pickFirst(u.rarity,""), element:normalizeElementDisplay(pickFirst(u.element,"")), stats:{atk,hp,spd,cost}, image:pickFirst(u.image,imgs[0],""), imagesLarge:imgs, imageVariants:Array.isArray(u.imageVariants)?u.imageVariants:[], forms:Array.isArray(u.forms)?u.forms:[], statsByForm:Array.isArray(u.statsByForm)?u.statsByForm:[], skillsByForm:Array.isArray(u.skillsByForm)?u.skillsByForm:[], leaderSkillName:pickFirst(u.leaderSkill?.name,""), leaderSkillDesc:pickFirst(u.leaderSkill?.description,""), activeSkills:Array.isArray(u.activeSkills)?u.activeSkills:[], passiveSkillDetails:Array.isArray(u.passiveSkillDetails)?u.passiveSkillDetails:[], activeSkillsByForm:normalizeFormSkillRows(u.forms,'activeSkills'), passiveSkillsByForm:normalizeFormSkillRows(u.forms,'passiveSkillDetails'), extraText:"" }); } return out; }
function normalizeWeapons(arr){ return arr.map(w=>{ const desc=pickFirst(w?.description,w?.flavorText,w?.profile,""); return {kind:"weapons",id:String(w?.id??w?.sourceId??""),name:pickFirst(w?.name,""),subtitle:pickFirst(w?.weaponType,w?.category,""),description:desc,flavorText:desc,rarity:pickFirst(w?.rarity,""),element:"",stats:{atk:pickFirst(w?.atk,w?.stats?.atk,""),hp:pickFirst(w?.hp,w?.stats?.hp,""),spd:"",cost:pickFirst(w?.stats?.cost,"")},image:pickFirst(w?.image,""),activeSkills:Array.isArray(w?.activeSkills)?w.activeSkills:[],passiveSkillDetails:Array.isArray(w?.passiveSkillDetails)?w.passiveSkillDetails:[],extraText:pickFirst(w?.effect,w?.source,"")}; }).filter(x=>x.id&&x.name); }
function normalizeAccessories(arr){ return arr.map(a=>{ const desc=pickFirst(a?.description,a?.flavorText,a?.profile,""); return {kind:"accessories",id:String(a?.id??a?.sourceId??""),name:pickFirst(a?.name,""),subtitle:pickFirst(a?.category,""),description:desc,flavorText:desc,rarity:pickFirst(a?.rarity,a?.stars,""),element:pickFirst(a?.element,""),stats:{atk:pickFirst(a?.atk,a?.stats?.atk,""),hp:pickFirst(a?.hp,a?.stats?.hp,""),spd:pickFirst(a?.spd,a?.stats?.spd,""),cost:pickFirst(a?.cost,a?.stats?.cost,"")},image:pickFirst(a?.image,""),activeSkills:Array.isArray(a?.activeSkills)?a.activeSkills:[],passiveSkillDetails:Array.isArray(a?.passiveSkillDetails)?a.passiveSkillDetails:[],extraText:""}; }).filter(x=>x.id&&x.name); }
function normalizeBosses(arr){ return arr.map(b=>{ const desc=pickFirst(b?.description,b?.flavorText,""); return {kind:"bosses",id:String(b?.id??b?.sourceId??""),name:pickFirst(b?.name,""),subtitle:pickFirst(b?.weaponType,b?.category,""),description:desc,flavorText:desc,rarity:pickFirst(b?.rarity,b?.stars,""),element:pickFirst(b?.element,""),stats:{atk:pickFirst(b?.atk,b?.stats?.atk,""),hp:pickFirst(b?.hp,b?.stats?.hp,""),spd:pickFirst(b?.spd,b?.stats?.spd,""),cost:""},image:pickFirst(b?.image,""),activeSkills:Array.isArray(b?.activeSkills)?b.activeSkills:[],passiveSkillDetails:Array.isArray(b?.passiveSkillDetails)?b.passiveSkillDetails:[],extraText:""}; }).filter(x=>x.id&&x.name); }
function kindLabel(kind){ if(kind==="characters")return"Character"; if(kind==="weapons")return"Weapon"; if(kind==="accessories")return"Accessory"; if(kind==="bosses")return"Boss"; return kind; }
function stateRowHtml(imgs){ if(!Array.isArray(imgs)||imgs.length<2)return""; const enc=encodeURIComponent(JSON.stringify(imgs)); const btns=imgs.map((_,i)=>`<button type="button" class="stateBtn ${i===0?"active":""}" data-idx="${i}" aria-label="State ${i+1}"></button>`).join(""); return `<div class="stateRow" data-imgs="${enc}">${btns}</div>`; }
function renderCard(item){ const imgsRaw=(item.kind==="characters"&&Array.isArray(item.imagesLarge)&&item.imagesLarge.length)?item.imagesLarge:(item.image?[item.image]:[]); const imgs=(imgsRaw||[]).filter(u=>u&&!isBadImgUrl(u)); const img=imgs.length?`<img src="${safeText(imgs[0])}" data-imgs="${safeText(encodeURIComponent(JSON.stringify(imgs)))}" data-state="0" alt="${safeText(item.name)}" onerror="markBadImgUrl(this.src);this.onerror=null;this.src=PLACEHOLDER_IMG;">`:`<div class="ph">?</div>`; const elClass=(item.kind==="characters"&&item.element)?` ${safeText(normalizeElementClass(item.element))}`:""; const chips=[]; chips.push(`<span class="tag kind">${safeText(kindLabel(item.kind))}</span>`); if(item.element)chips.push(`<span class="tag element">${safeText(normalizeElementDisplay(item.element))}</span>`); if(item.rarity)chips.push(`<span class="tag rarity">${safeText(item.rarity)}</span>`); const {atk,hp,spd,cost}=item.stats||{}; const statParts=[]; if(atk!==""&&atk!=null)statParts.push(`<div class="stat"><span class="statLabel">ATK</span><span class="statVal">${safeText(atk)}</span></div>`); if(hp!==""&&hp!=null)statParts.push(`<div class="stat"><span class="statLabel">HP</span><span class="statVal">${safeText(hp)}</span></div>`); if(spd!==""&&spd!=null)statParts.push(`<div class="stat"><span class="statLabel">SPD</span><span class="statVal">${safeText(spd)}</span></div>`); if(cost!==""&&cost!=null)statParts.push(`<div class="stat"><span class="statLabel">COST</span><span class="statVal">${safeText(cost)}</span></div>`); const extra=item.extraText?`<div class="panel"><div class="panelTitle">Info</div><div class="muted" style="white-space:pre-wrap">${safeText(item.extraText)}</div></div>`:""; return `
    <div class="unitCard${elClass}" data-kind="${safeText(item.kind)}" data-id="${safeText(item.id)}">
      <div class="unitLeft"><div class="unitThumb">${img}</div></div>
      <div class="meta">
        <div class="metaHeader">
          <div class="metaMain"><div class="nameBlock"><div class="unitName">${safeText(item.name)}</div><div class="unitTitle" style="display:block!important;visibility:visible!important;opacity:1!important">${safeText(item.subtitle||"")}</div></div>${item.kind==="characters"?stateRowHtml(imgs):""}</div>
          <div class="chipCol">${chips.join("")}</div>
        </div>
        <div class="unitDetails">
          ${statParts.length?`<div class="statLine">${statParts.join("")}</div>`:""}
          ${item.kind==="characters"&&(item.leaderSkillName||item.leaderSkillDesc)?`<div class="leaderBlock"><div class="leaderName">${safeText(item.leaderSkillName||"No Leader Skill")}</div><div class="leaderDesc">${safeText(item.leaderSkillDesc||"This unit does not provide a leader skill.")}</div></div>`:""}
          ${renderDescriptionPanel(item)}
          ${extra}
          ${renderSkillBoxes(item.kind==="characters"?"Active Skills":"Skills",item.activeSkills,"activeSkillPanel")}
          ${renderSkillBoxes(item.kind==="characters"?"Passive Skills":"Passives",item.passiveSkillDetails,"passiveSkillPanel")}
        </div>
      </div>
    </div>`; }
function render(){ const grid=$("catalogGrid"),status=$("statusText"); if(!grid)return; const q=(state.q||"").toLowerCase(),tokens=state.listTokens; let items=state.items; if(state.type!=="all")items=items.filter(i=>i.kind===state.type); items=items.filter(i=>{ if(tokens&&tokens.length)return matchesTokens(i,tokens); if(!q)return true; return `${i.name} ${i.subtitle} ${i.description} ${i.rarity} ${i.element} ${i.kind}`.toLowerCase().includes(q); }); if(status)status.textContent=tokens?.length?`${items.length} matched from pasted list`:`${items.length} items shown`; grid.innerHTML=items.map(renderCard).join(""); }
function stateDescriptionByIndex(card, idx){ const panel=card?.querySelector(".descriptionPanel"); const enc=panel?.getAttribute("data-descriptions")||""; let rows=[]; try{rows=JSON.parse(decodeURIComponent(enc))}catch{} return Array.isArray(rows)?rows[idx]:null; }
function applyStateToCard(card, idx){ if(!card)return; const descRow=stateDescriptionByIndex(card, idx); const descEl=card.querySelector(".descriptionText"); if(descEl&&descRow&&typeof descRow.description==="string")descEl.textContent=descRow.description; const titleEl=card.querySelector(".unitTitle"); if(titleEl&&descRow&&descRow.title)titleEl.textContent=descRow.title; }
function attachStateHandlers(root){ root.addEventListener("click",e=>{ const btn=e.target.closest(".stateBtn"); if(!btn)return; e.preventDefault(); e.stopPropagation(); const row=btn.closest(".stateRow"); const enc=row?.getAttribute("data-imgs")||""; let imgs=[]; try{imgs=JSON.parse(decodeURIComponent(enc))}catch{} if(!imgs.length)return; const card=btn.closest(".unitCard"); const imgEl=card?.querySelector(".unitThumb img"); if(!imgEl)return; const idx=parseInt(btn.getAttribute("data-idx")||"0",10); if(!Number.isFinite(idx)||idx<0||idx>=imgs.length)return; imgEl.src=imgs[idx]; imgEl.setAttribute("data-state",String(idx)); row.querySelectorAll(".stateBtn").forEach(b=>b.classList.remove("active")); btn.classList.add("active"); applyStateToCard(card, idx); }); root.addEventListener("click",e=>{ const img=e.target.closest(".unitThumb img"); if(!img)return; const card=img.closest(".unitCard"); if(!card)return; const enc=img.getAttribute("data-imgs")||card.querySelector(".stateRow")?.getAttribute("data-imgs")||""; let imgs=[]; try{imgs=JSON.parse(decodeURIComponent(enc))}catch{} if(!Array.isArray(imgs)||imgs.length<2)return; e.preventDefault(); e.stopPropagation(); const cur=parseInt(img.getAttribute("data-state")||"0",10); const next=(Number.isFinite(cur)?cur+1:1)%imgs.length; img.src=imgs[next]; img.setAttribute("data-state",String(next)); const row=card.querySelector(".stateRow"); if(row)row.querySelectorAll(".stateBtn").forEach((b,i)=>b.classList.toggle("active",i===next)); applyStateToCard(card, next); }); }
async function init(){ applyMobileViewClass(getMobileViewPref()); syncViewToggleText(); const hasEntryLoader=!!(window.EvertaleData&&window.EvertaleData.loadAllEntries); const [entries,legacyCharsJson,weaponsJson,accJson,bossesJson]=await Promise.all([hasEntryLoader?window.EvertaleData.loadAllEntries():null,fetchJsonOptional(DATA.characters),fetchJsonOptional(DATA.weapons),fetchJsonOptional(DATA.accessories),fetchJsonOptional(DATA.bosses)]); const legacyChars=toArray(legacyCharsJson,"characters"); const normalizedChars=entries?.characters?.length?normalizeCharacters(entries.characters):applyLegacyCharacterTitles(normalizeCharacters([]),legacyChars); const normalizedWeapons=entries?.weapons?.length?normalizeWeapons(entries.weapons):normalizeWeapons(toArray(weaponsJson,"weapons")); const normalizedAccessories=entries?.accessories?.length?normalizeAccessories(entries.accessories):normalizeAccessories(toArray(accJson,"accessories")); const normalizedBosses=entries?.bosses?.length?normalizeBosses(entries.bosses):normalizeBosses(toArray(bossesJson,"bosses")); state.items=[...normalizedChars,...normalizedWeapons,...normalizedAccessories,...normalizedBosses]; const search=$("catalogSearch"),typeSel=$("catalogType"),viewBtn=$("viewToggle"); search?.addEventListener("input",()=>{ const v=search.value||""; const maybeList=parseListTokens(v); state.listTokens=maybeList; state.q=maybeList?"":v; render(); }); search?.addEventListener("paste",e=>{ const pasted=(e.clipboardData||window.clipboardData)?.getData("text")||""; setTimeout(()=>{ const tokens=parseListTokens(pasted); if(tokens){ state.listTokens=tokens; state.q=""; render(); }},0); }); typeSel?.addEventListener("change",()=>{ state.type=String(typeSel.value||"all"); render(); }); viewBtn?.addEventListener("click",()=>{ const cur=getMobileViewPref(); const next=cur==="compact"?"detailed":"compact"; setMobileViewPref(next); applyMobileViewClass(next); syncViewToggleText(); }); window.addEventListener("resize",()=>applyMobileViewClass(getMobileViewPref())); render(); const grid=$("catalogGrid"); if(grid)attachStateHandlers(grid); }
document.addEventListener("DOMContentLoaded",()=>{ init().catch(err=>{ console.error(err); const status=$("statusText"); if(status)status.textContent=`Error: ${String(err.message||err)}`; }); });
