/* catalog.js — unified catalog renderer */

const PLACEHOLDER_IMG = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='128' height='128'><rect width='100%' height='100%' fill='%23121522'/><text x='50%' y='50%' dominant-baseline='middle' text-anchor='middle' fill='%23aab1d6' font-family='Arial' font-size='14'>No Image</text></svg>";
const BAD_IMG_CACHE_KEY = "evertale_bad_img_urls_v1";
const BAD_IMG_CACHE = new Set(safeJsonParse(localStorage.getItem(BAD_IMG_CACHE_KEY), []));
const DATA = { characters:"./apkfiles/entries/bundles/character_families.bundle.json", weapons:"./apkfiles/entries/bundles/weapons.bundle.json", accessories:"./apkfiles/entries/bundles/accessories.bundle.json", bosses:"./apkfiles/entries/bundles/bosses.bundle.json" };
const LS_MOBILE_VIEW_KEY = "evertale_mobile_view_v1";
const state = { items: [], q: "", type: "all", listTokens: null };
const $ = id => document.getElementById(id);

function safeJsonParse(raw, fallback){ try{return JSON.parse(raw)}catch{return fallback} }
function markBadImgUrl(url){ try{ if(!url)return; BAD_IMG_CACHE.add(url); localStorage.setItem(BAD_IMG_CACHE_KEY, JSON.stringify(Array.from(BAD_IMG_CACHE))); }catch{} }
function isBadImgUrl(url){ try{return !!url && BAD_IMG_CACHE.has(url)}catch{return false} }
function safeText(s){ return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;"); }
function pickFirst(...vals){ for(const v of vals){ if(v!==undefined&&v!==null&&v!=="") return v; } return ""; }
function normKey(s){ return String(s??"").toLowerCase().replace(/[\u2019']/g,"").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," "); }
function basenameNoExt(url){ const s=String(url||'').split(/[?#]/)[0].split('/').pop()||''; return s.replace(/\.[a-z0-9]+$/i,''); }
function normalizeElementDisplay(el){ const raw=String(el||'').trim(); return raw?raw.replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()):''; }
function normalizeElementClass(el){ const e=String(el||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,''); if(e==='fire'||e==='flame')return'el-fire'; if(e==='water'||e==='ice')return'el-water'; if(e==='storm'||e==='air'||e==='wind'||e==='thunder'||e==='lightning'||e==='electric')return'el-storm'; if(e==='earth'||e==='terra'||e==='ground')return'el-earth'; if(e==='light'||e==='life'||e==='holy')return'el-light'; if(e==='dark'||e==='death'||e==='shadow')return'el-dark'; return e?`el-${e}`:''; }
function getMobileViewPref(){ const v=localStorage.getItem(LS_MOBILE_VIEW_KEY); return (v==="detailed"||v==="compact")?v:"compact"; }
function setMobileViewPref(v){ localStorage.setItem(LS_MOBILE_VIEW_KEY,v); }
function applyMobileViewClass(view){ document.body.classList.add("page-catalog"); document.body.classList.remove("mobile-compact","mobile-detailed"); document.body.classList.add(view==="detailed"?"mobile-detailed":"mobile-compact"); }
function syncViewToggleText(){ const btn=$("viewToggle"); if(btn){ const v=getMobileViewPref(); btn.textContent=`View: ${v==="compact"?"Compact":"Detailed"}`; } }
async function fetchJson(url){ const res=await fetch(url,{cache:"no-store"}); if(!res.ok)throw new Error(`Failed to fetch ${url}: ${res.status}`); return await res.json(); }
async function fetchJsonOptional(url){ try{return await fetchJson(url)}catch(err){ console.warn('[Catalog] Optional JSON skipped:', url, err); return null; } }
function toArray(json,keyGuess){ if(Array.isArray(json))return json; if(json&&Array.isArray(json[keyGuess]))return json[keyGuess]; if(json&&Array.isArray(json.items))return json.items; return []; }

function parseListTokens(text){ const parts=String(text??"").split(/[\n\r,;\t]+/g).map(s=>s.trim()).filter(Boolean); if(parts.length<=1)return null; const tokens=[]; const seen=new Set(); for(const p of parts){ const k=normKey(p); if(!k||seen.has(k))continue; seen.add(k); tokens.push(k); } return tokens.length?tokens:null; }
function matchesTokens(item,tokens){ const id=normKey(item.id), sourceId=normKey(item.sourceId), name=normKey(item.name), sub=normKey(item.subtitle); for(const t of tokens){ if(t===id||t===sourceId||t===name||t===sub)return true; if(t.length>=4&&(name.includes(t)||sub.includes(t)||sourceId.includes(t)))return true; } return false; }

function imageUrlsFromCharacter(u){ const variants=Array.isArray(u.imageVariants)?u.imageVariants.map(v=>v&&v.url).filter(Boolean):[]; const large=Array.isArray(u.imagesLarge)?u.imagesLarge.filter(Boolean):[]; return variants.length?variants:(large.length?large:(u.image?[u.image]:[])); }
function normalizeFormSkillRows(forms, key){ return Array.isArray(forms)?forms.map(f=>({ state:f.state, sourceId:f.sourceId, rows:Array.isArray(f[key])?f[key]:[] })):[]; }
function normalizeCharacters(arr){ const seen=new Set(); const out=[]; for(const u of arr||[]){ const id=String(u?.id??u?.family??""); if(!id||seen.has(id))continue; seen.add(id); const atk=u.atk??u.stats?.atk??""; const hp=u.hp??u.stats?.hp??""; const spd=u.spd??u.stats?.spd??""; const cost=u.cost??u.stats?.cost??""; const imgs=imageUrlsFromCharacter(u); out.push({ kind:"characters", id, sourceId:u.sourceId||id, family:u.family||u.internal?.family||id, fileHandleOrder:u.fileHandleOrder??u.order??u.sourceOrder??null, order:u.fileHandleOrder??u.order??u.sourceOrder??null, name:pickFirst(u.name,id), subtitle:pickFirst(u.title,u.subtitle,""), description:pickFirst(u.description,""), descriptionByForm:Array.isArray(u.descriptionByForm)?u.descriptionByForm:[], rarity:pickFirst(u.rarity,""), element:normalizeElementDisplay(pickFirst(u.element,"")), stats:{atk,hp,spd,cost}, image:pickFirst(u.image,imgs[0],""), imagesLarge:imgs, imageVariants:Array.isArray(u.imageVariants)?u.imageVariants:[], forms:Array.isArray(u.forms)?u.forms:[], leaderSkillName:pickFirst(u.leaderSkill?.name,""), leaderSkillDesc:pickFirst(u.leaderSkill?.description,""), activeSkills:Array.isArray(u.activeSkills)?u.activeSkills:[], passiveSkillDetails:Array.isArray(u.passiveSkillDetails)?u.passiveSkillDetails:[], activeSkillsByForm:normalizeFormSkillRows(u.forms,'activeSkills'), passiveSkillsByForm:normalizeFormSkillRows(u.forms,'passiveSkillDetails'), extraText:"" }); } return out; }
function normalizeWeapons(arr){ return (arr||[]).map(w=>{ const raw=w?.raw||{}; const desc=pickFirst(w?.description,w?.flavorText,w?.profile,""); return {kind:"weapons",id:String(w?.id??w?.sourceId??""),fileHandleOrder:w?.fileHandleOrder??w?.order??w?.sourceOrder??null,order:w?.fileHandleOrder??w?.order??w?.sourceOrder??null,sourceId:String(w?.sourceId??w?.internal?.sourceId??w?.internal?.weaponId??w?.raw?.name??w?.id??""),family:String(w?.internal?.family??w?.family??""),name:pickFirst(w?.name,""),subtitle:pickFirst(w?.weaponType,w?.category,""),description:desc,flavorText:desc,rarity:pickFirst(w?.rarity,w?.stars,""),element:"",stats:{atk:pickFirst(w?.atk,w?.stats?.atk,raw.flatAttack,raw.baseAttack,raw.attack,""),hp:pickFirst(w?.hp,w?.stats?.hp,raw.flatMaxHp,raw.baseMaxHp,raw.hp,""),spd:"",cost:pickFirst(w?.cost,w?.stats?.cost,raw.cost,"")},image:pickFirst(w?.image,""),activeSkills:Array.isArray(w?.activeSkills)?w.activeSkills:[],passiveSkillDetails:Array.isArray(w?.passiveSkillDetails)?w.passiveSkillDetails:[],extraText:pickFirst(w?.effect,w?.source,"")}; }).filter(x=>x.id&&x.name); }
function normalizeAccessories(arr){ return (arr||[]).map(a=>{ const raw=a?.raw||{}; const desc=pickFirst(a?.description,a?.flavorText,a?.profile,""); return {kind:"accessories",id:String(a?.id??a?.sourceId??""),fileHandleOrder:a?.fileHandleOrder??a?.order??a?.sourceOrder??null,order:a?.fileHandleOrder??a?.order??a?.sourceOrder??null,sourceId:String(a?.sourceId??a?.internal?.sourceId??a?.raw?.name??a?.id??""),name:pickFirst(a?.name,""),subtitle:pickFirst(a?.category,""),description:desc,flavorText:desc,rarity:pickFirst(a?.rarity,a?.stars,raw.accessoryStars,""),element:pickFirst(a?.element,""),stats:{atk:pickFirst(a?.atk,a?.stats?.atk,raw.flatAttack,raw.baseAttack,raw.attack,""),hp:pickFirst(a?.hp,a?.stats?.hp,raw.flatMaxHp,raw.baseMaxHp,raw.hp,""),spd:pickFirst(a?.spd,a?.stats?.spd,raw.flatSpeed,raw.speed,""),cost:pickFirst(a?.cost,a?.stats?.cost,raw.cost,"")},image:pickFirst(a?.image,""),activeSkills:Array.isArray(a?.activeSkills)?a.activeSkills:[],passiveSkillDetails:Array.isArray(a?.passiveSkillDetails)?a.passiveSkillDetails:[],extraText:""}; }).filter(x=>x.id&&x.name); }
function normalizeBosses(arr){ return (arr||[]).map(b=>{ const raw=b?.raw||{}; const desc=pickFirst(b?.description,b?.flavorText,""); return {kind:"bosses",id:String(b?.id??b?.sourceId??""),fileHandleOrder:b?.fileHandleOrder??b?.order??b?.sourceOrder??null,order:b?.fileHandleOrder??b?.order??b?.sourceOrder??null,sourceId:String(b?.sourceId??b?.internal?.sourceId??b?.raw?.name??b?.id??""),name:pickFirst(b?.name,""),subtitle:pickFirst(b?.weaponType,b?.category,""),description:desc,flavorText:desc,rarity:pickFirst(b?.rarity,b?.stars,""),element:pickFirst(b?.element,""),stats:{atk:pickFirst(b?.atk,b?.stats?.atk,raw.baseAttack,raw.attack,""),hp:pickFirst(b?.hp,b?.stats?.hp,raw.baseMaxHp,raw.hp,""),spd:pickFirst(b?.spd,b?.stats?.spd,raw.speed,""),cost:""},image:pickFirst(b?.image,""),activeSkills:Array.isArray(b?.activeSkills)?b.activeSkills:[],passiveSkillDetails:Array.isArray(b?.passiveSkillDetails)?b.passiveSkillDetails:[],extraText:""}; }).filter(x=>x.id&&x.name); }

function legacyOrderMap(legacyRows){ const map=new Map(); let i=0; for(const row of legacyRows||[]){ const keys=[row?.id,row?.sourceId,row?.name,row?.internal?.sourceId,row?.internal?.monsterId,row?.internal?.weaponId,row?.internal?.equipmentId,row?.internal?.bossId].map(normKey).filter(Boolean); for(const k of keys){ if(!map.has(k))map.set(k,i); } i++; } return map; }
function sortByLegacyOrder(items, legacyRows){ const map=legacyOrderMap(legacyRows); if(!map.size)return items; return [...items].sort((a,b)=>{ const ak=[a.id,a.sourceId,a.name].map(normKey).find(k=>map.has(k)); const bk=[b.id,b.sourceId,b.name].map(normKey).find(k=>map.has(k)); const ai=ak?map.get(ak):999999; const bi=bk?map.get(bk):999999; if(ai!==bi)return ai-bi; return 0; }); }
function weaponOrderMap(weaponRows){ const map=new Map(); let i=0; for(const row of weaponRows||[]){ const keys=[row?.id,row?.sourceId,row?.name,row?.internal?.weaponId,row?.internal?.family,basenameNoExt(row?.image),basenameNoExt(row?.raw?.image)].map(normKey).filter(Boolean); for(const k of keys){ if(!map.has(k))map.set(k,i); } i++; } return map; }
function sortWeaponsByWeaponsJson(items, weaponRows){ const map=weaponOrderMap(weaponRows); if(!map.size)return items; return [...items].sort((a,b)=>{ const aKeys=[a.id,a.sourceId,a.family,a.name,basenameNoExt(a.image)].map(normKey); const bKeys=[b.id,b.sourceId,b.family,b.name,basenameNoExt(b.image)].map(normKey); const ak=aKeys.find(k=>map.has(k)); const bk=bKeys.find(k=>map.has(k)); const ai=ak?map.get(ak):999999; const bi=bk?map.get(bk):999999; if(ai!==bi)return ai-bi; return 0; }); }

function kindLabel(kind){ if(kind==="characters")return"Character"; if(kind==="weapons")return"Weapon"; if(kind==="accessories")return"Accessory"; if(kind==="bosses")return"Boss"; return kind; }
function skillMetaText(skill){ const parts=[]; if(skill&&skill.tu!==undefined&&skill.tu!==null&&skill.tu!=='')parts.push(String(skill.tu)+' TU'); const sp=skill?(skill.sp??skill.spirit):null; if(sp!==undefined&&sp!==null&&sp!=='')parts.push((Number(sp)>0?'+':'')+String(sp)+' SP'); if(skill&&skill.targeting)parts.push(String(skill.targeting)); return parts.join(' • '); }
function renderSkillBoxes(title, skills, kindClass){ const rows=Array.isArray(skills)?skills.filter(Boolean):[]; if(!rows.length)return ''; const boxes=rows.map(s=>{ const name=safeText((s&&s.name)||'Unnamed'); const meta=safeText(skillMetaText(s)); const desc=safeText((s&&s.description)||'').replace(/\n/g,'<br>'); return '<div class="skillBox"><div class="skillBoxHead"><strong>'+name+'</strong>'+(meta?'<span>'+meta+'</span>':'')+'</div>'+(desc?'<div class="skillBoxText">'+desc+'</div>':'')+'</div>'; }).join(''); return '<div class="panel skillPanel '+(kindClass||'')+'"><div class="panelTitle">'+safeText(title)+'</div><div class="skillBoxList">'+boxes+'</div></div>'; }
function renderDescriptionPanel(item){ const desc=String(item.description||item.flavorText||'').trim(); if(!desc)return ''; const payload=encodeURIComponent(JSON.stringify(item.descriptionByForm||[])); return `<div class="panel descriptionPanel" data-descriptions="${safeText(payload)}"><div class="panelTitle">Description</div><div class="muted descriptionText" style="white-space:pre-wrap">${safeText(desc)}</div></div>`; }
function stateRowHtml(imgs){ if(!Array.isArray(imgs)||imgs.length<2)return""; const enc=encodeURIComponent(JSON.stringify(imgs)); const btns=imgs.map((_,i)=>`<button type="button" class="stateBtn ${i===0?"active":""}" data-idx="${i}" aria-label="State ${i+1}"></button>`).join(""); return `<div class="stateRow" data-imgs="${enc}">${btns}</div>`; }
function renderCard(item){ const imgsRaw=(item.kind==="characters"&&Array.isArray(item.imagesLarge)&&item.imagesLarge.length)?item.imagesLarge:(item.image?[item.image]:[]); const imgs=(imgsRaw||[]).filter(u=>u&&!isBadImgUrl(u)); const img=imgs.length?`<img src="${safeText(imgs[0])}" data-imgs="${safeText(encodeURIComponent(JSON.stringify(imgs)))}" data-state="0" alt="${safeText(item.name)}" onerror="markBadImgUrl(this.src);this.onerror=null;this.src=PLACEHOLDER_IMG;">`:`<div class="ph">?</div>`; const elClass=(item.kind==="characters"&&item.element)?` ${safeText(normalizeElementClass(item.element))}`:""; const chips=[]; chips.push(`<span class="tag kind">${safeText(kindLabel(item.kind))}</span>`); if(item.element)chips.push(`<span class="tag element">${safeText(normalizeElementDisplay(item.element))}</span>`); if(item.rarity)chips.push(`<span class="tag rarity">${safeText(item.rarity)}</span>`); const {atk,hp,spd,cost}=item.stats||{}; const statParts=[]; if(atk!==""&&atk!=null)statParts.push(`<div class="stat"><span class="statLabel">ATK</span><span class="statVal">${safeText(atk)}</span></div>`); if(hp!==""&&hp!=null)statParts.push(`<div class="stat"><span class="statLabel">HP</span><span class="statVal">${safeText(hp)}</span></div>`); if(spd!==""&&spd!=null)statParts.push(`<div class="stat"><span class="statLabel">SPD</span><span class="statVal">${safeText(spd)}</span></div>`); if(cost!==""&&cost!=null)statParts.push(`<div class="stat"><span class="statLabel">COST</span><span class="statVal">${safeText(cost)}</span></div>`); const extra=item.extraText?`<div class="panel"><div class="panelTitle">Info</div><div class="muted" style="white-space:pre-wrap">${safeText(item.extraText)}</div></div>`:""; return `
    <div class="unitCard${elClass}" data-kind="${safeText(item.kind)}" data-id="${safeText(item.id)}" data-order="${safeText(item.order??item.fileHandleOrder??item.sourceOrder??'')}">
      <div class="unitLeft"><div class="unitThumb">${img}</div></div>
      <div class="meta">
        <div class="metaHeader">
          <div class="metaMain"><div class="nameBlock"><div class="unitName">${safeText(item.name)}</div><div class="unitTitle" style="display:block!important;visibility:visible!important;opacity:1!important">${safeText(item.subtitle||"")}</div></div>${item.kind==="characters"?stateRowHtml(imgs):""}</div>
          <div class="chipCol">${chips.join("")}</div>
        </div>
        <div class="unitDetails">
          ${statParts.length?`<div class="statLine">${statParts.join("")}</div>`:""}
          ${item.kind==="characters"&&(item.leaderSkillName||item.leaderSkillDesc)?`<div class="leaderBlock"><div class="leaderName">${safeText(item.leaderSkillName||"No Leader Skill")}</div><div class="leaderDesc">${safeText(item.leaderSkillDesc||"This unit does not provide a leader skill.")}</div></div>`:""}
          ${renderDescriptionPanel(item)}
          ${extra}
          ${renderSkillBoxes(item.kind==="characters"?"Active Skills":"Skills",item.activeSkills,"activeSkillPanel")}
          ${renderSkillBoxes(item.kind==="characters"?"Passive Skills":"Passives",item.passiveSkillDetails,"passiveSkillPanel")}
        </div>
      </div>
    </div>`; }

function render(){ const grid=$("catalogGrid"),status=$("statusText"); if(!grid)return; const q=(state.q||"").toLowerCase(),tokens=state.listTokens; let items=state.items; if(state.type!=="all")items=items.filter(i=>i.kind===state.type); items=items.filter(i=>{ if(tokens&&tokens.length)return matchesTokens(i,tokens); if(!q)return true; return `${i.name} ${i.subtitle} ${i.description} ${i.rarity} ${i.element} ${i.kind}`.toLowerCase().includes(q); }); if(status)status.textContent=tokens?.length?`${items.length} matched from pasted list`:`${items.length} items shown`; grid.innerHTML=items.map(renderCard).join(""); }
function stateDescriptionByIndex(card, idx){ const panel=card?.querySelector(".descriptionPanel"); const enc=panel?.getAttribute("data-descriptions")||""; let rows=[]; try{rows=JSON.parse(decodeURIComponent(enc))}catch{} return Array.isArray(rows)?rows[idx]:null; }
function applyStateToCard(card, idx){ if(!card)return; const descRow=stateDescriptionByIndex(card, idx); const descEl=card.querySelector(".descriptionText"); if(descEl&&descRow&&typeof descRow.description==="string")descEl.textContent=descRow.description; const titleEl=card.querySelector(".unitTitle"); if(titleEl&&descRow&&descRow.title)titleEl.textContent=descRow.title; }
function attachStateHandlers(root){ root.addEventListener("click",e=>{ const btn=e.target.closest(".stateBtn"); if(!btn)return; e.preventDefault(); e.stopPropagation(); const row=btn.closest(".stateRow"); const enc=row?.getAttribute("data-imgs")||""; let imgs=[]; try{imgs=JSON.parse(decodeURIComponent(enc))}catch{} if(!imgs.length)return; const card=btn.closest(".unitCard"); const imgEl=card?.querySelector(".unitThumb img"); if(!imgEl)return; const idx=parseInt(btn.getAttribute("data-idx")||"0",10); if(!Number.isFinite(idx)||idx<0||idx>=imgs.length)return; imgEl.src=imgs[idx]; imgEl.setAttribute("data-state",String(idx)); row.querySelectorAll(".stateBtn").forEach(b=>b.classList.remove("active")); btn.classList.add("active"); applyStateToCard(card, idx); }); root.addEventListener("click",e=>{ const img=e.target.closest(".unitThumb img"); if(!img)return; const card=img.closest(".unitCard"); if(!card)return; const enc=img.getAttribute("data-imgs")||card.querySelector(".stateRow")?.getAttribute("data-imgs")||""; let imgs=[]; try{imgs=JSON.parse(decodeURIComponent(enc))}catch{} if(!Array.isArray(imgs)||imgs.length<2)return; e.preventDefault(); e.stopPropagation(); const cur=parseInt(img.getAttribute("data-state")||"0",10); const next=(Number.isFinite(cur)?cur+1:1)%imgs.length; img.src=imgs[next]; img.setAttribute("data-state",String(next)); const row=card.querySelector(".stateRow"); if(row)row.querySelectorAll(".stateBtn").forEach((b,i)=>b.classList.toggle("active",i===next)); applyStateToCard(card, next); }); }

async function init(){
  applyMobileViewClass(getMobileViewPref());
  syncViewToggleText();

  if (!(window.EvertaleData && window.EvertaleData.loadAllEntries)) {
    throw new Error("Live data loader missing. Ensure data-loader.js is loaded before catalog.js.");
  }

  const entries = await window.EvertaleData.loadAllEntries();

  const normalizedChars = normalizeCharacters(entries.characters || []);
  const normalizedWeapons = normalizeWeapons(entries.weapons || []);
  const normalizedAccessories = normalizeAccessories(entries.accessories || []);
  const normalizedBosses = normalizeBosses(entries.bosses || []);

  state.items = [
    ...normalizedChars,
    ...normalizedWeapons,
    ...normalizedAccessories,
    ...normalizedBosses
  ];

  const search=$("catalogSearch"),typeSel=$("catalogType"),viewBtn=$("viewToggle");
  search?.addEventListener("input",()=>{ const v=search.value||""; const maybeList=parseListTokens(v); state.listTokens=maybeList; state.q=maybeList?"":v; render(); });
  search?.addEventListener("paste",e=>{ const pasted=(e.clipboardData||window.clipboardData)?.getData("text")||""; setTimeout(()=>{ const tokens=parseListTokens(pasted); if(tokens){ state.listTokens=tokens; state.q=""; render(); }},0); });
  typeSel?.addEventListener("change",()=>{ state.type=String(typeSel.value||"all"); render(); });
  viewBtn?.addEventListener("click",()=>{ const cur=getMobileViewPref(); const next=cur==="compact"?"detailed":"compact"; setMobileViewPref(next); applyMobileViewClass(next); syncViewToggleText(); });
  window.addEventListener("resize",()=>applyMobileViewClass(getMobileViewPref()));
  render();
  const grid=$("catalogGrid"); if(grid)attachStateHandlers(grid);
}
document.addEventListener("DOMContentLoaded",()=>{ init().catch(err=>{ console.error(err); const status=$("statusText"); if(status)status.textContent=`Error: ${String(err.message||err)}`; }); });
