/* catalog-lite.js — lightweight renderer for live catalog. */
(function(){
  const state={items:[],filtered:[],q:'',type:'all',rendered:0,token:0};
  const $=id=>document.getElementById(id);
  const safe=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const pick=(...vals)=>{for(const v of vals){if(v!==undefined&&v!==null&&v!=='')return v;}return''};
  const clean=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'');
  const strip=v=>String(v||'').split('/').pop().replace(/\.json$/i,'').replace(/^\d+_/,'');
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:''};
  const val=(e,raw,k,...f)=>num(pick(e?.stats?.[k],e?.[k],...f));
  const order=e=>num(pick(e?.fileHandleOrder,e?.sourceOrder,e?.order,e?.visualOrder,e?.raw?.bundleNumber));
  const file=e=>String(e?._bundleSourceFile||e?.file||e?.path||'').replace(/^\.\//,'');
  const attrJson=v=>{try{return safe(encodeURIComponent(JSON.stringify(v||[])))}catch{return''}};
  const idle=fn=>('requestIdleCallback'in window?requestIdleCallback(fn,{timeout:120}):setTimeout(fn,26));
  function elClass(el){const e=clean(el);if(['fire','flame'].includes(e))return'el-fire';if(['water','ice'].includes(e))return'el-water';if(['storm','air','wind','thunder','lightning','electric'].includes(e))return'el-storm';if(['earth','terra','ground'].includes(e))return'el-earth';if(['light','life','holy'].includes(e))return'el-light';if(['dark','death','shadow'].includes(e))return'el-dark';return e?`el-${e}`:'';}
  function displayEl(el){const raw=String(el||'').trim();return raw?raw.replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()):'';}
  function kindLabel(k){return k==='characters'?'Character':k==='weapons'?'Weapon':k==='accessories'?'Accessory':k==='bosses'?'Boss':k;}
  function skillRows(e,type){const key=type==='active'?'activeSkills':'passiveSkillDetails';if(Array.isArray(e?.[key]))return e[key];const src=type==='active'?e?.resolved?.activeSkills:e?.resolved?.passives;const out=[];if(src&&typeof src==='object'){for(const [id,d]of Object.entries(src)){const loc=d?.localization||{};out.push({id,name:loc.name||id,description:loc.description||''});}}return out;}
  function charImgs(u){const raw=Array.isArray(u.imageVariants)?u.imageVariants.map(v=>v&&v.url):Array.isArray(u.imagesLarge)?u.imagesLarge:(u.image?[u.image]:[]);return [...new Set((raw||[]).filter(Boolean))].slice(0,3);}
  function base(kind,e){const raw=e?.raw||{};const sourceId=String(e?.sourceId??e?.internal?.sourceId??e?.internal?.weaponId??e?.internal?.bossId??raw.name??e?.name??e?.id??'');return{kind,id:String(e?.id??e?.family??sourceId),sourceId,family:String(e?.family??e?.internal?.family??raw.family??strip(sourceId)),file:file(e),order:order(e),name:pick(e?.displayName,e?.title,e?.name,sourceId),subtitle:pick(e?.weaponType,raw.weaponPref,e?.category,e?.subtitle,kindLabel(kind)),description:pick(e?.description,e?.flavorText,e?.profile,e?.effect,raw.profile,''),rarity:pick(e?.rarity,e?.stars,raw.stars,raw.accessoryStars,''),element:displayEl(pick(e?.element,raw.element,'')),stats:{atk:val(e,raw,'atk',raw.flatAttack,raw.baseAttack,raw.attack),hp:val(e,raw,'hp',raw.flatMaxHp,raw.baseMaxHp,raw.hp),spd:val(e,raw,'spd',raw.flatSpeed,raw.speed),cost:val(e,raw,'cost',raw.cost)},activeSkills:skillRows(e,'active'),passiveSkillDetails:skillRows(e,'passive'),descriptionByForm:Array.isArray(e?.descriptionByForm)?e.descriptionByForm:[],leaderSkillName:pick(e?.leaderSkill?.name,''),leaderSkillDesc:pick(e?.leaderSkill?.description,'')};}
  function normalize(entries){
    const chars=(entries.characters||[]).map(e=>({...base('characters',e),name:pick(e.name,e.family,e.sourceId),subtitle:pick(e.title,e.subtitle,''),image:pick(e.image,charImgs(e)[0],''),images:charImgs(e)}));
    const weapons=(entries.weapons||[]).map(e=>{const x=base('weapons',e);return{...x,image:pick(e.image,x.sourceId?`https://ik.imagekit.io/r8fsa98s9/weapons/${x.sourceId}.png`:'')}});
    const accessories=(entries.accessories||[]).map(e=>{const x=base('accessories',e);return{...x,image:pick(e.image,x.sourceId?`https://ik.imagekit.io/r8fsa98s9/accessories/${x.sourceId}.png`:'')}});
    const bosses=(entries.bosses||[]).map(e=>{const x=base('bosses',e);return{...x,image:pick(e.image,x.sourceId?`https://ik.imagekit.io/r8fsa98s9/characters/${x.sourceId.replace(/Boss(?=\d+$)/,'')}.png`:'')}});
    return [...chars.sort((a,b)=>Number(b.order||0)-Number(a.order||0)),...weapons.sort((a,b)=>Number(b.order||0)-Number(a.order||0)),...accessories.sort((a,b)=>Number(a.order||999999)-Number(b.order||999999)),...bosses.sort((a,b)=>Number(a.order||999999)-Number(b.order||999999))].filter(x=>x.id&&x.name);
  }
  function stateBtns(imgs){if(!Array.isArray(imgs)||imgs.length<2)return'';const enc=attrJson(imgs.slice(0,3));return`<div class="stateRow" data-imgs="${enc}">${imgs.slice(0,3).map((_,i)=>`<button type="button" class="stateBtn ${i===0?'active':''}" data-idx="${i}" aria-label="State ${i+1}"></button>`).join('')}</div>`;}
  function card(item){
    const imgs=item.images?.length?item.images:(item.image?[item.image]:[]);const img=imgs[0]?`<img src="${safe(imgs[0])}" loading="lazy" decoding="async" fetchpriority="low" data-imgs="${attrJson(imgs)}" data-state="0" alt="${safe(item.name)}">`:'<div class="ph">?</div>';
    const chips=[`<span class="tag kind">${kindLabel(item.kind)}</span>`];if(item.element)chips.push(`<span class="tag element">${safe(item.element)}</span>`);if(item.rarity)chips.push(`<span class="tag rarity">${safe(item.rarity)}</span>`);
    const statHtml=Object.entries(item.stats||{}).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>`<div class="stat" data-stat="${k}"><span class="statLabel">${k.toUpperCase()}</span><span class="statVal">${safe(v)}</span></div>`).join('');
    const leader=item.kind==='characters'&&(item.leaderSkillName||item.leaderSkillDesc)?`<div class="leaderBlock"><div class="leaderName">${safe(item.leaderSkillName||'No Leader Skill')}</div><div class="leaderDesc">${safe(item.leaderSkillDesc||'This unit does not provide a leader skill.')}</div></div>`:'';
    const actions=item.activeSkills.length||item.passiveSkillDetails.length?`<div class="cardSkillActions"><button type="button" data-lite-skill="active">Active</button><button type="button" data-lite-skill="passive">Passive</button></div>`:'';
    return `<div class="unitCard ${elClass(item.element)}" data-kind="${item.kind}" data-id="${safe(item.id)}" data-source-id="${safe(item.sourceId)}" data-family="${safe(item.family)}" data-file="${safe(item.file)}" data-order="${safe(item.order)}" data-source-order="${safe(item.order)}" data-file-handle-order="${safe(item.order)}" data-active-skills="${attrJson(item.activeSkills)}" data-passive-skills="${attrJson(item.passiveSkillDetails)}"><div class="unitLeft"><div class="unitThumb">${img}</div></div><div class="meta"><div class="metaHeader"><div class="metaMain"><div class="nameBlock"><div class="unitName">${safe(item.name)}</div><div class="unitTitle" style="display:block!important;visibility:visible!important;opacity:1!important">${safe(item.subtitle)}</div></div>${item.kind==='characters'?stateBtns(imgs):''}</div><div class="chipCol">${chips.join('')}</div></div><div class="unitDetails">${statHtml?`<div class="statLine">${statHtml}</div>`:''}${leader}${actions}</div></div></div>`;
  }
  function filter(){const q=state.q.toLowerCase();let rows=state.items;if(state.type!=='all')rows=rows.filter(i=>i.kind===state.type);if(!q)return rows;return rows.filter(i=>`${i.name} ${i.subtitle} ${i.description} ${i.rarity} ${i.element} ${i.kind} ${i.sourceId}`.toLowerCase().includes(q));}
  function render(){const grid=$('catalogGrid'),status=$('statusText');if(!grid)return;const token=++state.token;state.filtered=filter();state.rendered=0;grid.innerHTML='';if(status)status.textContent=`${state.filtered.length} items shown`;renderMore(token,32);}
  function renderMore(token,count=48){const grid=$('catalogGrid');if(!grid||token!==state.token)return;if(document.hidden){setTimeout(()=>renderMore(token,count),250);return;}const start=state.rendered,end=Math.min(start+count,state.filtered.length);if(end<=start)return;grid.insertAdjacentHTML('beforeend',state.filtered.slice(start,end).map(card).join(''));state.rendered=end;if(end<state.filtered.length)idle(()=>renderMore(token,48));}
  function readSkills(card,type){let rows=[];try{rows=JSON.parse(decodeURIComponent(card?.getAttribute(type==='active'?'data-active-skills':'data-passive-skills')||''))}catch{}return (Array.isArray(rows)?rows:[]).map(s=>({name:s.name||s.id||'Unnamed Skill',meta:[s.tu?`${s.tu} TU`:'',s.sp!==undefined?`${Number(s.sp)>0?'+':''}${s.sp} SP`:''].filter(Boolean).join(' • '),desc:s.description||''}));}
  function openSkills(card,type){const rows=readSkills(card,type);if(!rows.length)return;let pop=$('liteSkillPop');if(!pop){document.body.insertAdjacentHTML('beforeend','<div class="lite-skill-pop" id="liteSkillPop" aria-hidden="true"><div class="lite-skill-card"><div class="lite-skill-head"><h3 id="liteSkillTitle">Skills</h3><button type="button" id="liteSkillClose" aria-label="Close">×</button></div><div class="lite-skill-list" id="liteSkillList"></div></div></div>');pop=$('liteSkillPop');$('liteSkillClose')?.addEventListener('click',()=>pop.classList.remove('open'));pop.addEventListener('click',e=>{if(e.target===pop)pop.classList.remove('open')});}const title=type==='active'?'Active Skills':'Passive Skills';$('liteSkillTitle').textContent=`${card.querySelector('.unitName')?.textContent?.trim()||'Selected'} — ${title}`;$('liteSkillList').innerHTML=rows.map(s=>`<div class="lite-skill-item"><strong>${safe(s.name)}</strong>${s.meta?`<span>${safe(s.meta)}</span>`:''}<p>${safe(s.desc)||'No description loaded.'}</p></div>`).join('');pop.classList.add('open');pop.setAttribute('aria-hidden','false');}
  function attach(){const grid=$('catalogGrid');if(!grid)return;grid.addEventListener('error',e=>{if(e.target&&e.target.tagName==='IMG'){e.target.replaceWith(Object.assign(document.createElement('div'),{className:'ph',textContent:'?'}));}},true);grid.addEventListener('click',e=>{const skill=e.target.closest('[data-lite-skill]');if(skill){openSkills(skill.closest('.unitCard'),skill.getAttribute('data-lite-skill'));return;}const btn=e.target.closest('.stateBtn');if(!btn)return;const card=btn.closest('.unitCard'),row=btn.closest('.stateRow'),img=card?.querySelector('.unitThumb img');let imgs=[];try{imgs=JSON.parse(decodeURIComponent(row?.dataset.imgs||''))}catch{}const idx=Number(btn.dataset.idx||0);if(!img||!imgs[idx])return;img.src=imgs[idx];img.dataset.state=String(idx);row.querySelectorAll('.stateBtn').forEach((b,i)=>b.classList.toggle('active',i===idx));});}
  async function init(){document.body.classList.add('page-catalog','mobile-compact');const entries=await window.EvertaleData.loadAllEntries();state.items=normalize(entries);const search=$('catalogSearch'),type=$('catalogType'),view=$('viewToggle');if(view)view.textContent='View: Compact';search?.addEventListener('input',()=>{clearTimeout(search._t);search._t=setTimeout(()=>{state.q=search.value||'';render();},150);});type?.addEventListener('change',()=>{state.type=type.value||'all';render();});render();attach();}
  document.addEventListener('DOMContentLoaded',()=>init().catch(err=>{console.error(err);const s=$('statusText');if(s)s.textContent=`Error: ${err.message||err}`;}));
})();
