(function(){
  const TZ='America/Los_Angeles';
  const themes={
    spring:['#153b2b','#3f7d57','#91d18b','#f1ffe8'],summer:['#0b2e4f','#145da0','#f7b733','#fff3b0'],autumn:['#2d1b12','#7b3f00','#c97a40','#f2c572'],winter:['#0a1f33','#183a5c','#7fb3d5','#eaf6ff'],newyear:['#0b1020','#1e2a78','#7c4dff','#d7c8ff'],valentine:['#3b0a23','#8b1e4f','#d94f70','#ffd1dc'],stpatrick:['#062b16','#0f6b3a','#5dbb63','#daf7dc'],easter:['#2e245c','#7c70d8','#f7c6e0','#fff7c2'],independence:['#081f5c','#b22234','#ffffff','#6ea8fe'],halloween:['#140b1f','#4a235a','#d35400','#f39c12'],thanksgiving:['#2b1a10','#8c4a1f','#d4a373','#f6e7cb'],christmas:['#072a1f','#0f5132','#b22222','#f3fff6']
  };
  const KEY='evertale_theme_pref_v1';
  function dateLA(){const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'numeric',day:'numeric'}).formatToParts(new Date());const g=t=>Number(p.find(x=>x.type===t)?.value||0);return{year:g('year'),month:g('month'),day:g('day')}}
  function inRange(m,d,sm,sd,em,ed){const x=m*100+d,s=sm*100+sd,e=em*100+ed;return s<=e?x>=s&&x<=e:x>=s||x<=e}
  function season(m,d){const x=m*100+d;if(x>=320&&x<621)return'spring';if(x>=621&&x<923)return'summer';if(x>=923&&x<1221)return'autumn';return'winter'}
  function easter(y){const a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=((h+l-7*m+114)%31)+1;return{month:mo,day:da}}
  function chooseTheme(){const n=dateLA(),ea=easter(n.year);if(inRange(n.month,n.day,12,1,12,31))return'christmas';if(inRange(n.month,n.day,1,1,1,10))return'newyear';if(inRange(n.month,n.day,2,1,2,15))return'valentine';if(inRange(n.month,n.day,3,10,3,18))return'stpatrick';if(inRange(n.month,n.day,ea.month,Math.max(1,ea.day-5),ea.month,Math.min(31,ea.day+2)))return'easter';if(inRange(n.month,n.day,7,1,7,7))return'independence';if(inRange(n.month,n.day,10,1,10,31))return'halloween';if(inRange(n.month,n.day,11,20,11,30))return'thanksgiving';return season(n.month,n.day)}
  function pref(){const v=localStorage.getItem(KEY)||'auto';return themes[v]||v==='auto'?v:'auto'}
  function applyTheme(){const p=pref(),key=p==='auto'?chooseTheme():p,colors=themes[key]||themes.winter,root=document.documentElement;root.style.setProperty('--bg',colors[0]);root.style.setProperty('--season-a',colors[0]);root.style.setProperty('--season-b',colors[1]);root.style.setProperty('--season-c',colors[2]);root.style.setProperty('--season-d',colors[3]);if(document.body){const n=dateLA();document.body.setAttribute('data-theme-key',key);document.body.setAttribute('data-theme-pref',p);document.body.setAttribute('data-theme-season',['spring','summer','autumn','winter'].includes(key)?key:season(n.month,n.day));document.body.setAttribute('data-theme-holiday',['spring','summer','autumn','winter'].includes(key)?'':key)}}
  window.EvertaleTheme={themes,chooseTheme,applyTheme,getPreference:pref,setPreference(v){localStorage.setItem(KEY,themes[v]||v==='auto'?v:'auto');applyTheme();}};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',applyTheme,{once:true}):applyTheme();
})();
