export const STARS_TO_LEVEL_MAX=[30,30,30,30,60,80,100];
export const AWAKENING_6_CHARACTER=[1,1.22,1.44,1.66,1.88];
export const AWAKENING_6_WEAPON=[1,1.19,1.33,1.44,1.55];
export const AWAKENING_FLAT={4:{hp:201,atk:40},5:{hp:412,atk:82},6:{hp:1239,atk:248}};
export const AWAKENING_MULTIPLIERS=AWAKENING_6_CHARACTER;
export function clampNumber(v,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):min;}
export function clampInt(v,min,max){return Math.round(clampNumber(v,min,max));}
export function trunc0(v){const n=Number(v)||0;return n<0?Math.ceil(n):Math.floor(n);}
export function roundEven(v){const n=Number(v)||0,f=Math.floor(n),d=n-f;return Math.abs(d-.5)<=1e-9?(f%2===0?f:f+1):Math.round(n);}
export function percentScale(value,scalar){const v=Number(value)||0,s=Number(scalar)||0;return s>=0?v*(1+s):v/(1-s);}
export function maxLevel(stars,evolvedStars,extraEvolves){const s=clampInt(stars,0,6),e=clampInt(evolvedStars,0,6);return (STARS_TO_LEVEL_MAX[s]||30)+(20*clampInt(extraEvolves,0,5))+(s===3&&e===4?20:0);}
export function extraEvolvesForLevel(level,stars=6,evolvedStars=6){return clampInt(Math.ceil(Math.max(0,clampInt(level,1,200)-maxLevel(stars,evolvedStars,0))/20),0,5);}
export function limitBreakState(level,stars=6,evolvedStars=6){const x=extraEvolvesForLevel(level,stars,evolvedStars);return{state:x?`Limit Break ${x}`:'Normal',tier:x,multiplier:1+.08*x};}
export function limitBreakMultiplier(level,stars=6,evolvedStars=6){return limitBreakState(level,stars,evolvedStars).multiplier;}
export function statFormula({level,levelOverride=0,baseStat,bonusLevels=0}){const l=clampInt(levelOverride||level||1,1,200),e=trunc0(Math.min(1.5*l,l+clampNumber(bonusLevels,0,999)));return (Number(baseStat)||0)*(1+.025*(e-30));}
export function awakeningBonus(awakening,evolvedStars,forWeapon=false){const a=clampInt(awakening,0,4),e=clampInt(evolvedStars,0,6);if(e===4)return 1+.05*a;if(e===5)return 1+.075*a;if(e===6)return (forWeapon?AWAKENING_6_WEAPON:AWAKENING_6_CHARACTER)[a]||1;return 1;}
export function awakeningFlat(awakening,evolvedStars,statName){const t=AWAKENING_FLAT[clampInt(evolvedStars,0,6)];return t?(t[statName]||0)*clampInt(awakening,0,4):0;}
export function characterPlusFlat(pluses){const b=clampInt(pluses,0,300);return b<=90?{hp:b*14,atk:b*3}:{hp:1260+(b-90)*311,atk:270+(b-90)*73};}
export function weaponPlusFlat(pluses){const b=Math.max(0,clampInt(pluses,0,10000));return{hp:b*14,atk:b*3};}
export function passiveFlatStats(passives=[],awakening=0){const out={hp:0,atk:0},active=(Array.isArray(passives)?passives:[]).map(String).slice(0,Math.min(6,clampInt(awakening,0,4)+2));for(const id of active){const hp=id.match(/^PlusHPBoostLv(\d+)$/),atk=id.match(/^PlusAttackBoostLv(\d+)$/);if(hp)out.hp+=400*clampInt(hp[1],0,9);if(atk)out.atk+=100*clampInt(atk[1],0,9);}return out;}
export function boostFlat(boost){return characterPlusFlat(boost);}
export function accountRankBP(rank){const r=clampInt(rank,0,300);return Math.floor(2000000*Math.pow(r,3)/Math.pow(300,3));}
export function totalPowerRarityScalar(stars){const s=clampInt(stars,0,6);return s===5?1.5:s===6?2:1;}
export function calculateStatApprox(c){const s=clampInt(c.stars??6,0,6),e=clampInt(c.evolvedStars??s,0,6),x=Number.isFinite(Number(c.extraEvolves))?clampInt(c.extraEvolves,0,5):extraEvolvesForLevel(c.level,s,e),ref=Number.isFinite(Number(c.refine))?clampNumber(c.refine,0,10000):clampNumber(c.potential??0,0,100)*100,p=1+ref/10000,lv=statFormula(c),prog=lv*p*(1+.08*x)*awakeningBonus(c.awakening??0,e,!!c.forWeapon),plus=(c.forWeapon?weaponPlusFlat(c.pluses??0):characterPlusFlat(c.pluses??0))[c.statName]||0,cl=maxLevel(s,e,s>3?5:0),cos=c.cosmo?statFormula({level:cl,levelOverride:cl,baseStat:c.baseStat})*p*.07:0,flat=c.useAwakeningFlat?awakeningFlat(c.awakening??0,e,c.statName):0;return trunc0(prog+flat+plus+cos+(Number(c.externalFlat)||0));}
export function projectWhiteStatFromRef(config){return calculateStatApprox({baseStat:config.baseStat??config.refStat200,statName:config.statName||'hp',level:config.level,stars:config.stars??6,evolvedStars:config.evolvedStars??6,extraEvolves:config.extraEvolves,awakening:config.copies??config.awakening??0,potential:config.potential??0,pluses:config.boostFlatValue??config.pluses??0,externalFlat:config.fellowshipFlat??0,cosmo:!!config.isAscended});}
export function reverseRawBase(){throw new Error('reverseRawBase requires a captured runtime sample.');}
export const reverseRefStat200=reverseRawBase;
export function calculateWeaponEngine(c={}){const level=clampInt(c.level??200,1,200),stars=clampInt(c.stars??6,0,6),evolvedStars=clampInt(c.evolvedStars??stars,0,6),common={level,stars,evolvedStars,extraEvolves:c.extraEvolves,awakening:c.awakening??0,pluses:c.pluses??c.boost??0,refine:c.refine,potential:c.potential??0,bonusLevels:c.bonusLevels??0,forWeapon:true,cosmo:false,useAwakeningFlat:true},hp=calculateStatApprox({...common,statName:'hp',baseStat:c.baseHP??c.baseMaxHp??c.refHP??0}),atk=calculateStatApprox({...common,statName:'atk',baseStat:c.baseATK??c.baseAttack??c.refATK??0});return{hp,atk,power:roundEven(6*hp+30*atk)};}
export function calculateAccessoryEngine(c={}){const hp=Number(c.hp??c.flatMaxHp??0)||0,atk=Number(c.atk??c.flatAttack??0)||0,spd=Number(c.spd??c.flatSpeed??0)||0;return{hp,atk,spd,power:6*hp+30*atk+180*spd};}
export function calculateCoreDamage(c={}){const scalar=c.conditionalScalar==null?Number(c.abilityScalar||0):Number(c.conditionalScalar||0),boost=(Array.isArray(c.damageBoosts)?c.damageBoosts:[]).reduce((s,v)=>s+(Number(v)||0),0),base=roundEven(percentScale(Number(c.attack)||0,scalar+boost)),boosted=roundEven(percentScale(base,Number(c.extraAttackScalar)||0));if(c.ignoreElement)return Math.max(0,boosted);return Math.max(0,trunc0(boosted*((Number(c.elementFactor??1)||1)+(Number(c.attackerMastery)||0)-(Number(c.defenderMastery)||0))));}
export function calculateMasterUnitEngine(c={}){const level=clampInt(c.level,1,200),stars=clampInt(c.stars??6,0,6),evolvedStars=clampInt(c.evolvedStars??stars,0,6),awakening=clampInt(c.copies??c.awakening??0,0,4),pluses=clampInt(c.boost??c.pluses??0,0,300),potential=clampNumber(c.potential??0,0,100),mastery=Math.max(0,Number(c.mastery??c.limitBreakLevel??0)||0),passive=passiveFlatStats(c.passives||[],awakening),common={level,stars,evolvedStars,extraEvolves:c.extraEvolves,awakening,pluses,potential,refine:c.refine,cosmo:!!c.isAscended},whiteHP=calculateStatApprox({...common,statName:'hp',baseStat:c.baseHP??c.baseMaxHp??c.refHP??0,externalFlat:(Number(c.flatFellowshipHP??0)||0)+passive.hp}),whiteATK=calculateStatApprox({...common,statName:'atk',baseStat:c.baseATK??c.baseAttack??c.refATK??0,externalFlat:(Number(c.flatFellowshipATK??0)||0)+passive.atk}),gear=Object.assign({wepHP:0,wepATK:0,accHP:0,accATK:0,accSPD:0},c.gear||{}),equipmentHP=(Number(gear.wepHP)||0)+(Number(gear.accHP)||0),equipmentATK=(Number(gear.wepATK)||0)+(Number(gear.accATK)||0),equipmentPower=(Number(gear.wepHP)||0)*6+(Number(gear.wepATK)||0)*30+(Number(gear.accHP)||0)*6+(Number(gear.accATK)||0)*30+(Number(gear.accSPD)||0)*180,basePower=roundEven((6*whiteHP+30*whiteATK)*totalPowerRarityScalar(stars)),characterPower=roundEven((6*whiteHP+30*whiteATK)*totalPowerRarityScalar(stars)*(1+.005*mastery)),unitPower=characterPower+equipmentPower+(Number(c.lockedPlatoonOffset??c.bonus??0)||0),accountRankPower=c.includeRank?accountRankBP(c.playerRank):0;return{whiteHP,whiteATK,cardHP:whiteHP,cardATK:whiteATK,blueHP:whiteHP+equipmentHP,blueATK:whiteATK+equipmentATK,equipmentHP,equipmentATK,unitPower,battalionPower:unitPower+accountRankPower,accountRankPower,equipmentPower,passiveFlat:passive,masteryPower:characterPower-basePower,characterPower,trace:{level,stars,evolvedStars,awakening,pluses,potential,mastery,whiteHP,whiteATK,characterPower,equipmentPower,passive}};}
